name: Test
on: [push]
jobs:
  build-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies
        run: pnpm install
        working-directory: apps/src

      - name: Build
        run: pnpm run build
        working-directory: apps/src
